### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by drook** [verm/freebsd-stable-diffusion#4]
Can easily be solved by installing graphics/libglvnd and/or graphics/linux-c7-libglvnd.

````
(automatic) [root@bsdrookie ~/sd/stable-diffusion-webui]# LD_PRELOAD=/home/emz/sd/stable-diffusion-webui/dummy-uvm.so python3 launch.py
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
Commit hash: 226d840e84c5f306350b0681945989b86760e616
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments: --medvram
Fontconfig error: Cannot load default config file
Traceback (most recent call last):
  File "/usr/home/emz/sd/stable-diffusion-webui/launch.py", line 362, in <module>
    start()
  File "/usr/home/emz/sd/stable-diffusion-webui/launch.py", line 353, in start
    import webui
  File "/usr/home/emz/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/usr/home/emz/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/usr/home/emz/sd/stable-diffusion-webui/modules/shared.py", line 12, in <module>
    import modules.interrogate
  File "/usr/home/emz/sd/stable-diffusion-webui/modules/interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "/usr/home/emz/sd/stable-diffusion-webui/modules/modelloader.py", line 7, in <module>
    from basicsr.utils.download_util import load_file_from_url
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/basicsr/__init__.py", line 3, in <module>
    from .archs import *
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/basicsr/archs/__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/basicsr/utils/__init__.py", line 4, in <module>
    from .img_process_util import USMSharp, usm_sharp
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/basicsr/utils/img_process_util.py", line 1, in <module>
    import cv2
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/emz/sd/conda/envs/automatic/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
(automatic) [root@bsdrookie ~/sd/stable-diffusion-webui]#
````

**Comment by verm** [comment]
You would need linux-c7-libglvnd for it to work thanks for letting me know this package is missing I'll modify the tutorial to add it!  Interesting nobody I asked to test complained about it I'll have to ask if they fixed it or installed something that required it already.  Thank you for the report.
